//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODAMS.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransferLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransferLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MODAMS.Localization.TransferLabels", typeof(TransferLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgement Date.
        /// </summary>
        public static string AcknowledgementDate {
            get {
                return ResourceManager.GetString("AcknowledgementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission for Acknowledgement Date.
        /// </summary>
        public static string SubmissionForAcknowledgementDate {
            get {
                return ResourceManager.GetString("SubmissionForAcknowledgementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer By.
        /// </summary>
        public static string TransferBy {
            get {
                return ResourceManager.GetString("TransferBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Date.
        /// </summary>
        public static string TransferDate {
            get {
                return ResourceManager.GetString("TransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer From Store.
        /// </summary>
        public static string TransferFrom {
            get {
                return ResourceManager.GetString("TransferFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Notes.
        /// </summary>
        public static string TransferNotes {
            get {
                return ResourceManager.GetString("TransferNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Number.
        /// </summary>
        public static string TransferNumber {
            get {
                return ResourceManager.GetString("TransferNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Status.
        /// </summary>
        public static string TransferStatus {
            get {
                return ResourceManager.GetString("TransferStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to Store.
        /// </summary>
        public static string TransferTo {
            get {
                return ResourceManager.GetString("TransferTo", resourceCulture);
            }
        }
    }
}
